export const SET_LANGUAGE="SET_LANGUAGE"

export const LOGIN_USER_START='LOGIN_USER_START'
export const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL='LOGIN_USER_FAIL'
export const LOGIN_USER_INIT='LOGIN_USER_INIT'
